use std::error::Error;

mod repository;

#[tokio::main]
async fn main() -> Result<(), Box<dyn Error>> {
    dotenvy::dotenv()?;
    let repository = 

    Ok(())
}
